# Semgrep configuration for advanced SAST
# Semgrep finds bugs and enforces code standards
# https://semgrep.dev/

rules:
  # SQL Injection detection
  - id: sql-injection
    pattern-either:
      - pattern: |
          $CURSOR.execute($QUERY)
      - pattern: |
          $CURSOR.executemany($QUERY, ...)
    message: "Potential SQL injection - use parameterized queries"
    languages: [python]
    severity: ERROR

  # Command injection detection
  - id: command-injection
    pattern-either:
      - pattern: os.system($CMD)
      - pattern: subprocess.call($CMD, shell=True)
      - pattern: subprocess.run($CMD, shell=True)
      - pattern: subprocess.Popen($CMD, shell=True)
    message: "Potential command injection - avoid shell=True and validate inputs"
    languages: [python]
    severity: ERROR

  # Hardcoded secrets detection
  - id: hardcoded-password
    pattern-either:
      - pattern: password = "..."
      - pattern: api_key = "..."
      - pattern: secret = "..."
    message: "Potential hardcoded secret - use environment variables"
    languages: [python]
    severity: ERROR

  # Pickle deserialization (RCE risk)
  - id: unsafe-pickle
    pattern-either:
      - pattern: pickle.loads($DATA)
      - pattern: pickle.load($FILE)
    message: "Pickle deserialization can lead to RCE - use json instead"
    languages: [python]
    severity: ERROR

  # Eval/exec usage (code injection risk)
  - id: dangerous-eval
    pattern-either:
      - pattern: eval($EXPR)
      - pattern: exec($CODE)
    message: "eval/exec can execute arbitrary code - extremely dangerous"
    languages: [python]
    severity: ERROR

  # Debug mode enabled in production
  - id: debug-enabled
    pattern: DEBUG = True
    message: "Debug mode should not be enabled in production"
    languages: [python]
    severity: WARNING
