#!/bin/bash
# Branch Cleanup Script for sonrai-zombie-blaster
# Generated by Kiro AI - Run with caution!

set -e  # Exit on error

echo "🧹 Branch Cleanup Script"
echo "======================="
echo ""

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Function to prompt for confirmation
confirm() {
    read -p "$1 (y/n) " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        return 0
    else
        return 1
    fi
}

echo "Current branch:"
git branch --show-current
echo ""

echo "All branches:"
git branch -a
echo ""

# Phase 1: Delete merged branches
echo -e "${YELLOW}Phase 1: Delete merged branches${NC}"
echo "These branches are fully merged into main and safe to delete:"
echo "  - bugfix/controller-dismiss-messages"
echo "  - feature/cyber-attack-bosses"
echo "  - feature/jit-access-quest"
echo "  - feature/pause-and-lobby-return"
echo "  - feature/service-protection-quest"
echo "  - fix/powerup-system"
echo "  - refactor/split-game-engine"
echo ""

if confirm "Delete these 7 merged branches?"; then
    echo -e "${GREEN}Deleting merged branches...${NC}"
    git branch -d bugfix/controller-dismiss-messages 2>/dev/null && echo "✓ Deleted bugfix/controller-dismiss-messages" || echo "⊘ Already deleted or doesn't exist"
    git branch -d feature/cyber-attack-bosses 2>/dev/null && echo "✓ Deleted feature/cyber-attack-bosses" || echo "⊘ Already deleted or doesn't exist"
    git branch -d feature/jit-access-quest 2>/dev/null && echo "✓ Deleted feature/jit-access-quest" || echo "⊘ Already deleted or doesn't exist"
    git branch -d feature/pause-and-lobby-return 2>/dev/null && echo "✓ Deleted feature/pause-and-lobby-return" || echo "⊘ Already deleted or doesn't exist"
    git branch -d feature/service-protection-quest 2>/dev/null && echo "✓ Deleted feature/service-protection-quest" || echo "⊘ Already deleted or doesn't exist"
    git branch -d fix/powerup-system 2>/dev/null && echo "✓ Deleted fix/powerup-system" || echo "⊘ Already deleted or doesn't exist"
    git branch -d refactor/split-game-engine 2>/dev/null && echo "✓ Deleted refactor/split-game-engine" || echo "⊘ Already deleted or doesn't exist"
    echo ""
else
    echo -e "${YELLOW}Skipped Phase 1${NC}"
    echo ""
fi

# Phase 2: Merge current work (if on feature/player-damage-system)
echo -e "${YELLOW}Phase 2: Merge current work${NC}"
CURRENT_BRANCH=$(git branch --show-current)

if [ "$CURRENT_BRANCH" = "feature/player-damage-system" ]; then
    echo "You're on feature/player-damage-system"
    echo "This branch has recent bug fixes and tests that should be merged to main."
    echo ""
    
    if confirm "Merge feature/player-damage-system to main?"; then
        echo -e "${GREEN}Merging to main...${NC}"
        git checkout main
        git merge feature/player-damage-system
        echo "✓ Merged feature/player-damage-system to main"
        echo ""
        
        if confirm "Push to origin/main?"; then
            git push origin main
            echo "✓ Pushed to origin/main"
        fi
        echo ""
        
        if confirm "Delete feature/player-damage-system branch?"; then
            git branch -d feature/player-damage-system
            echo "✓ Deleted feature/player-damage-system"
        fi
        echo ""
    else
        echo -e "${YELLOW}Skipped Phase 2${NC}"
        echo ""
    fi
else
    echo "Not on feature/player-damage-system, skipping merge."
    echo "Current branch: $CURRENT_BRANCH"
    echo ""
fi

# Phase 3: Review stale branches
echo -e "${YELLOW}Phase 3: Review stale unmerged branches${NC}"
echo "These branches are NOT merged and may be stale:"
echo ""

# Check feature/arcade-mode
if git show-ref --verify --quiet refs/heads/feature/arcade-mode; then
    echo -e "${RED}feature/arcade-mode${NC}"
    echo "  Last commit: $(git log feature/arcade-mode --oneline -1)"
    echo "  Analysis: OLD arcade mode implementation (main has newer version)"
    echo ""
    
    if confirm "Show diff with main?"; then
        git diff main feature/arcade-mode --stat | head -20
        echo ""
    fi
    
    if confirm "DELETE feature/arcade-mode? (Force delete - not merged)"; then
        git branch -D feature/arcade-mode
        echo "✓ Deleted feature/arcade-mode"
        echo ""
    fi
fi

# Check feature/multi-level-progression
if git show-ref --verify --quiet refs/heads/feature/multi-level-progression; then
    echo -e "${RED}feature/multi-level-progression${NC}"
    echo "  Last commit: $(git log feature/multi-level-progression --oneline -1)"
    echo "  Analysis: Platformer work (may be superseded by main)"
    echo ""
    
    if confirm "Show diff with main?"; then
        git diff main feature/multi-level-progression --stat | head -20
        echo ""
    fi
    
    if confirm "DELETE feature/multi-level-progression? (Force delete - not merged)"; then
        git branch -D feature/multi-level-progression
        echo "✓ Deleted feature/multi-level-progression"
        echo ""
    fi
fi

# Check levels
if git show-ref --verify --quiet refs/heads/levels; then
    echo -e "${RED}levels${NC}"
    echo "  Last commit: $(git log levels --oneline -1)"
    echo "  Analysis: Platformer refactor (may have unique display scaling fixes)"
    echo ""
    
    if confirm "Show diff with main?"; then
        git diff main levels --stat | head -20
        echo ""
    fi
    
    if confirm "DELETE levels? (Force delete - not merged)"; then
        git branch -D levels
        echo "✓ Deleted levels"
        echo ""
    fi
fi

# Final summary
echo ""
echo -e "${GREEN}✅ Cleanup Complete!${NC}"
echo ""
echo "Remaining branches:"
git branch -a
echo ""
echo "Branch count: $(git branch | wc -l | xargs)"
echo ""
echo "📋 See .kiro/BRANCH_CLEANUP_ANALYSIS.md for detailed analysis"
